parameters:
    zendesk.apiservice.class: Malwarebytes\ZendeskBundle\Service\ApiService

services:
    zendesk.api:
        class: %zendesk.apiservice.class%
        arguments: [%zendesk_api_key%, %zendesk_api_user%, %zendesk_api_subdomain%]
